import {
  FaIdCard,
  FaPhoneAlt,
  FaBuilding,
  FaCreditCard,
  FaCheckCircle,
  FaCamera,
  FaUser,
  FaUsers,
  FaMapMarkerAlt,
  FaBolt,
  FaFileAlt,
  FaCar,
  FaShieldAlt,
  FaHistory,
} from "react-icons/fa";

const verificationConfig = {
  nin: {
    heroTitle: "Verify Your",
    heroTitleContinue: "in seconds",
    heroHighlight: "National ID ",
    heroSubtitle:
      "Enter details, pay securely and get accurate results instantly.",
    heroImage: require("../../images/uganda.png"),
    breadcrumb: ["Verify Identity", "National ID Verification"],
    idTypeLabel: "National Identification Number",
    fields: [
      {
        name: "idNumber",
        label: "National ID",
        placeholder: "Enter 11 digits National ID",
        type: "text",
        maxLength: 20,
        showCounter: true,
        required: true,
      },
      {
        name: "subjectPhone",
        label: "Subject Contact Number (for consent)",
        placeholder: "Enter subject's phone number",
        type: "text",
        maxLength: 15,
        showCounter: true,
        required: false,
      },
      {
        name: "subjectEmail",
        label: "Subject Email (for consent)",
        placeholder: "Enter subject's email address",
        type: "email",
        maxLength: 100,
        showCounter: false,
        required: false,
      },
    ],
    youWillGet: [
      { icon: FaUser, text: "Full personal details" },
      { icon: FaCamera, text: "Photo" },
      { icon: FaUsers, text: "Next of kin details" },
      { icon: FaCheckCircle, text: "Verification status" },
      { icon: FaBolt, text: "Instant results" },
    ],
    sampleResult: {
      name: "Grace Ojocheneimi David",
      identifier: "National ID: 43832856233",
      tags: ["Full Name", "Photo", "Date of Birth", "And more..."],
    },
    serviceName: "National ID Verification",
    serviceCode: "NATIONAL_ID",
    apiServiceName: "National ID",
    serviceFieldKey: "idNumber",
    priceIndex: 0,
    requiresConsent: true,
    trustBar: [
      { title: "Secure & Private", desc: "Your data is protected" },
      { title: "Instant Results", desc: "Get results in seconds" },
      { title: "Trusted Platform", desc: "Government compliant" },
      { title: "500,000+ Users", desc: "Trust e-raia" },
    ],
  },

  phone: {
    heroTitle: "Verify a ",
    heroHighlight: "Phone Number",
    heroSubtitle:
      "Enter a phone number, pay securely and get verification results instantly.",
    heroImage: require("../../images/phone_number_verification.png"),
    breadcrumb: ["Verify Identity", "Phone Verification"],
    idTypeLabel: "Phone Number Verification",
    fields: [
      {
        name: "phone",
        label: "Phone Number",
        placeholder: "Enter phone number (e.g. 08031234567)",
        type: "text",
        maxLength: 11,
        showCounter: true,
        required: true,
      },
    ],
    youWillGet: [
      { icon: FaUser, text: "Owner information" },
      { icon: FaPhoneAlt, text: "Network details" },
      { icon: FaCheckCircle, text: "Verification status" },
      { icon: FaMapMarkerAlt, text: "Region details" },
      { icon: FaBolt, text: "Instant results" },
    ],
    sampleResult: {
      name: "Adebayo John O.",
      identifier: "Phone: 0803 *** 5678",
      tags: ["Owner Name", "Network", "Status", "And more..."],
    },
    serviceName: "Phone Verification",
    serviceCode: "PHONE",
    apiServiceName: "Phone",
    serviceFieldKey: "phone",
    priceIndex: 9,
    trustBar: [
      { title: "Secure & Private", desc: "Your data is protected" },
      { title: "Instant Results", desc: "Get results in seconds" },
      { title: "Trusted Platform", desc: "Government compliant" },
      { title: "500,000+ Users", desc: "Trust e-raia" },
    ],
  },

  business: {
    heroTitle: "Verify a Business",
    heroHighlight: "in seconds",
    heroSubtitle:
      "Enter company details, pay securely and get accurate results instantly.",
    heroImage: require("../../images/business_verification2.png"),
    breadcrumb: ["Verify Business", "Business Verification"],
    idTypeLabel: "Business Registration (RC Number / Business Name)",
    fields: [
      {
        name: "rc",
        label: "RC Number",
        placeholder: "Enter RC Number",
        type: "text",
        maxLength: 10,
        showCounter: false,
        required: false,
        eitherOr: "business",
      },
      {
        name: "business_name",
        label: "Business Name",
        placeholder: "Enter Business Name",
        type: "text",
        maxLength: 100,
        showCounter: false,
        required: false,
        eitherOr: "business",
      },
    ],
    youWillGet: [
      { icon: FaBuilding, text: "Company details" },
      { icon: FaUsers, text: "Directors & shareholders" },
      { icon: FaFileAlt, text: "Registration status" },
      { icon: FaCheckCircle, text: "Verification status" },
      { icon: FaBolt, text: "Instant results" },
    ],
    sampleResult: {
      name: "ABC Technologies Ltd",
      identifier: "RC: 123456",
      tags: ["Company Name", "Directors", "Status", "And more..."],
    },
    serviceName: "Business Verification",
    serviceCode: "BUSINESS",
    apiServiceName: "Business",
    serviceFieldKey: "rc",
    priceIndex: 2,
    trustBar: [
      { title: "Secure & Private", desc: "Your data is protected" },
      { title: "Instant Results", desc: "Get results in seconds" },
      { title: "Trusted Platform", desc: "Government compliant" },
      { title: "500,000+ Users", desc: "Trust e-raia" },
    ],
  },

  "business-name": {
    heroTitle: "Verify a Business",
    heroHighlight: "Name",
    heroSubtitle:
      "Search by business name, pay securely and get accurate results instantly.",
    heroImage: require("../../images/business_verification.png"),
    breadcrumb: ["Verify Business", "Business Name Verification"],
    idTypeLabel: "Business Name Search",
    fields: [
      {
        name: "business_name",
        label: "Business Name",
        placeholder: "Enter business name",
        type: "text",
        maxLength: 100,
        showCounter: false,
        required: true,
      },
      {
        name: "purpose",
        label: "Purpose (optional)",
        placeholder: "Select purpose",
        type: "select",
        required: false,
        options: [
          "Due Diligence",
          "Partnership Verification",
          "Investment Check",
          "Compliance",
          "Other",
        ],
      },
    ],
    youWillGet: [
      { icon: FaBuilding, text: "Company details" },
      { icon: FaUsers, text: "Directors & shareholders" },
      { icon: FaFileAlt, text: "Registration status" },
      { icon: FaCheckCircle, text: "Verification status" },
      { icon: FaBolt, text: "Instant results" },
    ],
    sampleResult: {
      name: "XYZ Enterprises",
      identifier: "BN: 3456789",
      tags: ["Business Name", "Directors", "Status", "And more..."],
    },
    serviceName: "Business Name Verification",
    serviceCode: "BUSINESS_NAME",
    apiServiceName: "Business Name",
    serviceFieldKey: "business_name",
    priceIndex: 3,
    trustBar: [
      { title: "Secure & Private", desc: "Your data is protected" },
      { title: "Instant Results", desc: "Get results in seconds" },
      { title: "Trusted Platform", desc: "Government compliant" },
      { title: "500,000+ Users", desc: "Trust e-raia" },
    ],
  },

  bvn: {
    heroTitle: "Verify Your ",
    heroHighlight: "BVN in seconds",
    heroSubtitle:
      "Enter your BVN, pay securely and get financial verification results instantly.",
    heroImage: require("../../images/credit_profile.png"),
    breadcrumb: ["Verify Financial", "BVN Verification"],
    idTypeLabel: "Bank Verification Number (BVN)",
    fields: [
      {
        name: "bvn",
        label: "BVN",
        placeholder: "Enter 11 digits BVN",
        type: "text",
        maxLength: 11,
        showCounter: true,
        required: true,
      },
    ],
    youWillGet: [
      { icon: FaUser, text: "Full personal details" },
      { icon: FaCreditCard, text: "Financial profile" },
      { icon: FaCheckCircle, text: "Verification status" },
      { icon: FaBolt, text: "Instant results" },
    ],
    sampleResult: {
      name: "John Doe",
      identifier: "BVN: 22345678901",
      tags: ["Full Name", "Bank Details", "Status", "And more..."],
    },
    serviceName: "BVN Verification",
    serviceCode: "BVN",
    apiServiceName: "BVN",
    serviceFieldKey: "bvn",
    priceIndex: 4,
    requiresConsent: true,
    bureaus: [
      { id: "crc", label: "Credit Risk Certification (CRC)", fieldName: "crc" },
      { id: "firstCentral", label: "First Central", fieldName: "firstCentral" },
      {
        id: "creditRegistry",
        label: "Credit Registry",
        fieldName: "creditRegistry",
      },
    ],
    allBureausDiscount: { ugx: 3000, usd: 0.97 },
    trustBar: [
      { title: "Secure & Private", desc: "Your data is protected" },
      { title: "Instant Results", desc: "Get results in seconds" },
      { title: "Trusted Platform", desc: "Government compliant" },
      { title: "500,000+ Users", desc: "Trust e-raia" },
    ],
  },

  alien: {
    heroTitle: "Verify Your Alien Card",
    heroHighlight: "in seconds",
    heroTitleContinue: "",
    heroSubtitle:
      "Enter details, pay securely and get accurate results instantly.",
    heroImage: require("../../images/phone_number_verification.png"),
    breadcrumb: ["Verify Identity", "Alien Card Verification"],
    idTypeLabel: "Alien Card Number",
    fields: [
      {
        name: "idNumber",
        label: "Alien Card Number",
        placeholder: "Enter Alien Card Number",
        type: "text",
        maxLength: 20,
        showCounter: true,
        required: true,
      },
      {
        name: "subjectPhone",
        label: "Subject Contact Number (for consent)",
        placeholder: "Enter subject's phone number",
        type: "text",
        maxLength: 15,
        showCounter: true,
        required: false,
      },
      {
        name: "subjectEmail",
        label: "Subject Email (for consent)",
        placeholder: "Enter subject's email address",
        type: "email",
        maxLength: 100,
        showCounter: false,
        required: false,
      },
    ],
    youWillGet: [
      { icon: FaUser, text: "Full personal details" },
      { icon: FaIdCard, text: "Card details" },
      { icon: FaCheckCircle, text: "Verification status" },
      { icon: FaBolt, text: "Instant results" },
    ],
    sampleResult: {
      name: "Jane Doe",
      identifier: "Alien Card: ******1234",
      tags: ["Full Name", "Card Number", "Status", "And more..."],
    },
    serviceName: "Alien Card Verification",
    serviceCode: "ALIEN_CARD",
    apiServiceName: "Alien Card",
    serviceFieldKey: "idNumber",
    priceIndex: 0,
    requiresConsent: true,
    trustBar: [
      { title: "Secure & Private", desc: "Your data is protected" },
      { title: "Instant Results", desc: "Get results in seconds" },
      { title: "Trusted Platform", desc: "Government compliant" },
      { title: "500,000+ Users", desc: "Trust e-raia" },
    ],
  },

  nin_ug: {
    heroTitle: "Verify Your",
    heroHighlight: "National ID (Uganda)",
    heroSubtitle:
      "Enter details, pay securely and get accurate results instantly.",
    heroImage: require("../../images/uganda.png"),
    breadcrumb: ["Verify Identity", "National ID Verification (UG)"],
    idTypeLabel: "National Identification Number (Uganda)",
    countryCode: "UG",
    serviceCode: "NATIONAL_ID",
    apiServiceName: "National ID",
    fields: [
      {
        name: "idNumber",
        label: "National ID Number",
        placeholder: "Enter your Uganda National ID number",
        type: "text",
        maxLength: 14,
        showCounter: true,
        required: true,
      },
      {
        name: "subjectPhone",
        label: "Subject Contact Number (for consent)",
        placeholder: "Enter subject's phone number",
        type: "text",
        maxLength: 15,
        showCounter: true,
        required: false,
      },
      {
        name: "subjectEmail",
        label: "Subject Email (for consent)",
        placeholder: "Enter subject's email address",
        type: "email",
        maxLength: 100,
        showCounter: false,
        required: false,
      },
    ],
    youWillGet: [
      { icon: FaUser, text: "Full personal details" },
      { icon: FaCamera, text: "Photo" },
      { icon: FaCheckCircle, text: "Verification status" },
      { icon: FaBolt, text: "Instant results" },
    ],
    sampleResult: {
      name: "Okello James",
      identifier: "National ID: CM840000****",
      tags: ["Full Name", "Date of Birth", "Status", "And more..."],
    },
    serviceName: "Uganda National ID Verification",
    serviceFieldKey: "idNumber",
    priceIndex: 0,
    requiresConsent: true,
    trustBar: [
      { title: "Secure & Private", desc: "Your data is protected" },
      { title: "Instant Results", desc: "Get results in seconds" },
      { title: "Trusted Platform", desc: "Government compliant" },
      { title: "500,000+ Users", desc: "Trust e-raia" },
    ],
  },

  vehicle_ug: {
    heroTitle: "Check ",
    heroHighlight: "Vehicle History (Uganda)",
    heroSubtitle:
      "Verify a vehicle by VIN to reduce fraud and make safer purchase decisions.",
    heroImage: require("../../images/VIN_verification_platform_in_nigeria.png"),
    breadcrumb: ["Verify Vehicle", "Vehicle Verification (UG)"],
    idTypeLabel: "Vehicle Identification Number (VIN) — Uganda",
    countryCode: "UG",
    serviceCode: "VIN",
    apiServiceName: "VIN",
    fields: [
      {
        name: "idNumber",
        label: "VIN (Vehicle Identification Number)",
        placeholder: "Enter VIN",
        type: "text",
        maxLength: 17,
        showCounter: true,
        required: true,
      },
    ],
    youWillGet: [
      { icon: FaCar, text: "Vehicle details" },
      { icon: FaHistory, text: "Ownership history" },
      { icon: FaShieldAlt, text: "Theft / watchlist status" },
      { icon: FaCheckCircle, text: "Verification status" },
      { icon: FaBolt, text: "Instant results" },
    ],
    sampleResult: {
      name: "Toyota Land Cruiser 2019",
      identifier: "VIN: ******5678",
      tags: ["Make/Model", "Ownership", "Status", "And more..."],
    },
    serviceName: "Uganda Vehicle Verification",
    serviceFieldKey: "idNumber",
    priceIndex: 1,
    requiresConsent: false,
    trustBar: [
      { title: "Secure & Private", desc: "Your data is protected" },
      { title: "Instant Results", desc: "Get results in seconds" },
      { title: "Trusted Platform", desc: "Government compliant" },
      { title: "500,000+ Users", desc: "Trust e-raia" },
    ],
  },

  vehicle: {
    heroTitle: "Check ",
    heroHighlight: "Vehicle History",
    heroSubtitle:
      "Verify a vehicle by VIN to reduce fraud and make safer purchase decisions.",
    heroImage: require("../../images/uganda.png"),
    breadcrumb: ["Verify Vehicle", "Vehicle Verification"],
    idTypeLabel: "Vehicle Identification Number (VIN)",
    fields: [
      {
        name: "idNumber",
        label: "Vehicle Identification Number (VIN)",
        placeholder: "Enter VIN",
        type: "text",
        maxLength: 17,
        showCounter: true,
        required: true,
      },
    ],
    youWillGet: [
      { icon: FaCar, text: "Vehicle details" },
      { icon: FaHistory, text: "Ownership history" },
      { icon: FaShieldAlt, text: "Theft / watchlist status" },
      { icon: FaCheckCircle, text: "Verification status" },
      { icon: FaBolt, text: "Instant results" },
    ],
    sampleResult: {
      name: "Toyota Corolla 2018",
      identifier: "VIN: ******5678",
      tags: ["Make/Model", "Ownership", "Status", "And more..."],
    },
    serviceName: "Vehicle Verification",
    serviceCode: "VIN",
    apiServiceName: "VIN",
    serviceFieldKey: "idNumber",
    priceIndex: 5,
    trustBar: [
      { title: "Secure & Private", desc: "Your data is protected" },
      { title: "Instant Results", desc: "Get results in seconds" },
      { title: "Trusted Platform", desc: "Government compliant" },
      { title: "500,000+ Users", desc: "Trust e-raia" },
    ],
  },
};

export default verificationConfig;
