const termsOfServiceFR = `
<p>Bienvenue sur citoyen.africa ou citoyen. citoyen est fourni par Biosec Solutions Limited. Veuillez lire attentivement ces Conditions d'utilisation («&nbsp;Conditions&nbsp;») et la Politique de confidentialité, car elles constituent un accord contraignant entre Vous et Biosec Solutions Limited («&nbsp;Biosec&nbsp;» ou «&nbsp;Nous&nbsp;»). Ces Conditions clarifient les attentes et définissent nos droits et obligations respectifs concernant votre utilisation de citoyen.</p>
<p>Ces Conditions régissent votre utilisation de citoyen lié à ces Conditions. Dans ces Conditions, citoyen.ng fait référence à l'ensemble des plateformes citoyen détenues et contrôlées par Biosec et aux services offerts sur celles-ci. Vous acceptez automatiquement ces Conditions et notre Politique de confidentialité simplement en utilisant ou en vous connectant à citoyen.</p>
<p>Ces Conditions peuvent être modifiées de temps à autre. Nous publierons toute modification de nos Conditions sur citoyen et vous informerons des mises à jour en révisant la date de «&nbsp;Dernière mise à jour&nbsp;» figurant en haut de la page. Si les modifications sont importantes, nous nous efforcerons de fournir un avis plus visible (comme une notification par e-mail).</p>
<p>Veuillez noter que nous pouvons actuellement ou à l'avenir offrir différents services. Votre utilisation de nos produits ou services est fournie par Biosec en vertu d'un accord séparé exécuté manuellement ou numériquement. Ces conditions supplémentaires font partie de votre accord avec nous si vous utilisez les services ou vous connectez à citoyen.</p>
<h5>Capacité d'accepter les Conditions</h5>
<p>Vous affirmez que vous avez 18 ans ou plus, ou que vous possédez le consentement légal d'un parent ou tuteur, et que vous êtes pleinement capable et compétent pour accepter les conditions, obligations, affirmations, déclarations et garanties énoncées dans les présentes Conditions, et pour respecter et vous conformer à ces Conditions.</p>
<h5>Votre Compte</h5>
<p>Vous pouvez créer un compte et spécifier un mot de passe afin d'utiliser certains services ou fonctionnalités sur citoyen. Vous acceptez que toutes les informations que vous fournissez seront complètes, véridiques et correctes. Si vos informations changent à tout moment, vous acceptez de les mettre à jour pour refléter ces changements.</p>
<p>Vous ne pouvez pas partager votre compte ou votre mot de passe avec qui que ce soit. Veuillez garder votre mot de passe confidentiel. Vous serez seul responsable de la sécurisation de votre nom d'utilisateur et mot de passe, et de toute utilisation de citoyen utilisant votre adresse e-mail ou mot de passe. Si vous pensez que votre compte a été compromis à tout moment, veuillez nous en informer à info@citoyen.ng. Vous serez seul responsable de toute utilisation de citoyen sous votre compte et mot de passe. Vous acceptez de nous informer rapidement si vous avez connaissance de toute utilisation ou divulgation non autorisée de votre mot de passe. Nous nous réservons le droit de refuser ou de révoquer l'utilisation de tout nom d'utilisateur à notre discrétion.</p>
<h5>Modifications</h5>
<p>Nous nous réservons le droit de modifier citoyen à tout moment, avec ou sans préavis. Par exemple, nous pouvons ajouter ou supprimer des fonctionnalités, et nous pouvons suspendre ou arrêter complètement une fonctionnalité particulière. Nous nous réservons également le droit de facturer des frais pour l'une de nos fonctionnalités à tout moment. Si vous n'aimez pas les modifications, vous pouvez cesser d'utiliser citoyen à tout moment.</p>
<h5>Résiliation</h5>
<p>Nous pouvons à tout moment cesser d'exploiter tout ou partie de citoyen ou désactiver sélectivement certains aspects de citoyen. Vous pouvez cesser d'utiliser citoyen à tout moment, à condition que vous reconnaissiez et acceptiez que tout contenu publié par vous avant cette date continuera d'être disponible sur et via citoyen. Nous pouvons résilier votre utilisation de citoyen si vous violez ces Conditions, avec ou sans préavis.</p>
<h5>Votre Utilisation de citoyen</h5>
<p>Votre utilisation de citoyen sera conforme à toutes les lois applicables. Vous ne tenterez pas de contourner ou de violer une fonctionnalité de sécurité de citoyen, y compris l'accès à des fonctionnalités, zones interactives, informations ou profils pour lesquels vous n'avez pas d'autorisation. Dans le cadre de votre utilisation de citoyen, vous acceptez de ne pas&nbsp;:</p>
<ul>
<li>interférer avec, ou tenter d'interférer avec, le fonctionnement normal de citoyen ou l'utilisation de citoyen par tout autre utilisateur, notamment en surchargeant, inondant, spammant ou faisant planter citoyen ou ses systèmes sous-jacents, ou en modifiant tout profil, avis ou autre information fournie par un utilisateur&nbsp;;</li>
<li>publier, partager, lier ou soumettre tout contenu ou matériel diffamatoire, calomnieux, portant atteinte à la vie privée ou aux droits de publicité, vulgaire, grossier, indécent, obscène, sexuellement explicite ou exploiteur&nbsp;;</li>
<li>utiliser citoyen pour harceler, intimider, menacer, humilier, traquer ou autrement intimider tout autre utilisateur ou tiers&nbsp;;</li>
<li>publier, partager, lier ou soumettre tout contenu ou matériel constituant un discours de haine, promouvant la violence contre un groupe ou une personne, ou autrement répréhensible&nbsp;;</li>
<li>publier, partager, lier ou soumettre tout contenu ou matériel frauduleux, faux, trompeur ou mensonger&nbsp;;</li>
<li>publier, partager ou divulguer toute information personnellement identifiable concernant un tiers&nbsp;;</li>
<li>usurper l'identité d'une autre personne ou entité, ou suggérer ou revendiquer faussement une affiliation avec une autre personne ou entité&nbsp;;</li>
<li>chercher à monétiser citoyen, notamment en fournissant des avis ou des recommandations contre paiement ou autre contrepartie d'un tiers&nbsp;;</li>
<li>collecter, stocker ou analyser des informations sur d'autres utilisateurs, sauf autorisation de cet utilisateur&nbsp;;</li>
<li>nous exposer à une responsabilité civile ou pénale&nbsp;;</li>
<li>violer toute loi applicable ou encourager un comportement qui constituerait une infraction pénale.</li>
</ul>
<p>Si nous déterminons (à notre seule discrétion) que vous avez agi de manière inappropriée, nous nous réservons le droit de supprimer du contenu, de résilier votre compte, de vous interdire d'utiliser citoyen et de prendre toute autre mesure légale appropriée. L'utilisation de citoyen ne vous confère pas la propriété de droits de propriété intellectuelle sur le contenu auquel vous accédez. Vous ne pouvez pas utiliser le contenu de citoyen sans obtenir notre autorisation ou celle de son propriétaire, sauf si la loi le permet.</p>
<p>Lorsque vous utilisez citoyen ou nous envoyez des communications via citoyen, vous communiquez avec nous par voie électronique. Vous consentez à recevoir par voie électronique toute communication liée à votre utilisation de citoyen. Nous pouvons communiquer avec vous par e-mail ou en publiant des avis sur citoyen. Vous acceptez que tous les accords, avis, divulgations et autres communications qui vous sont fournis par voie électronique satisfont à toute exigence légale selon laquelle ces communications doivent être écrites. Veuillez noter qu'en soumettant du contenu, en créant un compte utilisateur ou en nous fournissant votre adresse e-mail, adresse postale ou numéro de téléphone, vous acceptez que nous ou nos agents puissions vous contacter à cette adresse ou numéro conformément à notre Politique de confidentialité.</p>
<h5>Paiement en Ligne</h5>
<p>Notre Service permet le paiement en ligne des frais nécessaires en utilisant des services de paiement en ligne tiers. Vous serez responsable des informations de paiement que vous fournissez à ces services de paiement en ligne et nous ne serons pas tenus responsables des informations invalides fournies, ni de l'initialisation, la mise en œuvre, la progression ou l'achèvement d'un éventuel processus de remboursement découlant de votre utilisation de nos Solutions et Services.</p>
<p>Nous vous encourageons à vérifier l'exactitude des critères de recherche. Vous ne serez pas remboursé si les informations de recherche sont incorrectes ou n'existent pas.</p>
<h5>Accès du Sujet aux Données Enregistrées</h5>
<p>Notre service repose sur le consentement lorsque cela est applicable. Le consentement du sujet est requis avant que les informations ne soient divulguées à un utilisateur demandeur. Vous ne serez pas remboursé si un sujet n'a pas accès au numéro de téléphone ou à l'adresse e-mail enregistré dans la base de données associée, ou si le sujet refuse son consentement.</p>
<h5>Exactitude et Intégrité des Données</h5>
<p>citoyen est un agrégateur de données et ne renvoie que les résultats rapportés par les sources de données des institutions obligées. citoyen n'est pas responsable de l'exactitude ou de l'intégrité des données renvoyées et ne fournit pas une telle garantie. Toute demande concernant l'exactitude ou l'intégrité des données doit être adressée à l'institution obligée.</p>
<h5>Propriété Intellectuelle</h5>
<p>Entre vous et Biosec, citoyen, y compris tout le contenu, graphiques, audio, vidéo, images, marques, logos et autres éléments sur citoyen, ainsi que son logiciel sous-jacent, algorithmes, bases de données, apparence et agencement, sont la propriété intellectuelle de Biosec, soumis aux droits d'auteur et autres protections de propriété intellectuelle. La marque et le logo de citoyen sont des marques de Biosec. Tous les droits sur citoyen et le logiciel non expressément accordés dans les présentes sont réservés par nous. Nous vous accordons et vous acceptez une licence non exclusive, non transférable et révocable pour utiliser le logiciel uniquement pour votre propre utilisation de citoyen et conformément aux présentes Conditions.</p>
<p>Si vous estimez qu'un contenu sur citoyen viole vos droits d'auteur, vous pouvez demander la suppression du contenu en nous contactant à dpo@biosec.com.ng. Nous nous engageons à utiliser des efforts commercialement raisonnables pour enquêter sur chaque réclamation.</p>
<h5>Réseaux Sociaux</h5>
<p>citoyen peut inclure des fonctionnalités qui fonctionnent en conjonction avec certains sites de réseaux sociaux tiers que vous visitez, tels que Facebook, Instagram, YouTube, Vimeo et Twitter. Bien que votre utilisation de ces fonctionnalités soit régie par les présentes Conditions, votre accès et utilisation des sites de réseaux sociaux tiers sont régis par les conditions d'utilisation et autres accords publiés sur ces sites. Vous êtes responsable de vous assurer que votre utilisation de ces sites est conforme à leurs conditions d'utilisation applicables.</p>
<h5>Clause de non-garantie</h5>
<p>citoyen EST FOURNI «&nbsp;EN L'ÉTAT&nbsp;» ET «&nbsp;SELON LA DISPONIBILITÉ&nbsp;». NOUS DÉCLINONS TOUTE REPRÉSENTATION ET GARANTIE, EXPRESSE OU IMPLICITE, CONCERNANT citoyen OU SON CONTENU, Y COMPRIS, MAIS SANS S'Y LIMITER, LES GARANTIES IMPLICITES DE QUALITÉ MARCHANDE, D'ADAPTATION À UN USAGE PARTICULIER ET DE NON-VIOLATION DES DROITS DE PROPRIÉTÉ INTELLECTUELLE DE TIERS. BIOSEC NE FOURNIT AUCUNE GARANTIE OU REPRÉSENTATION CONCERNANT L'EXACTITUDE, LA ROBUSTESSE, LA SÉCURITÉ OU L'EXHAUSTIVITÉ DE citoyen OU DE SON CONTENU. NOUS NE FOURNISSONS AUCUNE GARANTIE CONCERNANT LA DISPONIBILITÉ OU LA FIABILITÉ DE citoyen OU QUE citoyen SERA ACCESSIBLE À UN MOMENT SPÉCIFIQUE. TOUTE UTILISATION DE citoyen EST À VOS PROPRES RISQUES. SI VOUS N'ÊTES PAS SATISFAIT DE citoyen, VOTRE SEUL RECOURS EST DE CESSER D'UTILISER LE SERVICE ET D'OBTENIR UN REMBOURSEMENT POUR LES PAIEMENTS ANTICIPÉS, LE CAS ÉCHÉANT, COMME INDIQUÉ DANS LES PRÉSENTES CONDITIONS.</p>
<h5>Limitation de Responsabilité</h5>
<p>SAUF LORSQUE INTERDIT, BIOSEC NE SERA PAS RESPONSABLE DES DOMMAGES DIRECTS, INDIRECTS, SPÉCIAUX, ACCESSOIRES, CONSÉCUTIFS OU EXEMPLAIRES DÉCOULANT DE VOTRE UTILISATION DE citoyen OU DE L'UTILISATION DE citoyen PAR UN TIERS. CES EXCLUSIONS INCLUENT, SANS LIMITATION, LES DOMMAGES POUR PERTE DE PROFITS, PERTE DE DONNÉES, PANNE INFORMATIQUE OU VIOLATION DE VOS DROITS PAR UN TIERS, MÊME SI UNE PARTIE A ÉTÉ INFORMÉE DE LEUR POSSIBILITÉ. EN AUCUN CAS LA RESPONSABILITÉ TOTALE DE BIOSEC ENVERS UN UTILISATEUR INDIVIDUEL LIÉE À L'UTILISATION DE citoyEN N'EXCÉDERA LE MONTANT TOTAL QUE VOUS NOUS AVEZ PAYÉ POUR L'UTILISATION DE citoyen, QUE CETTE RESPONSABILITÉ SOIT FONDÉE SUR UN CONTRAT, UN DÉLIT OU AUTRE.</p>
<h5>Indemnisation</h5>
<p>Vous acceptez par les présentes d'indemniser, défendre et dégager de toute responsabilité Biosec et ses affiliés, ainsi que leurs propriétaires, membres, administrateurs, dirigeants, gestionnaires, employés, entrepreneurs indépendants, sous-traitants, agents et représentants («&nbsp;Parties Indemnisées&nbsp;») contre toute réclamation, action en justice, procédure, responsabilité, taxes, dommages, pertes, honoraires d'avocat, coûts et dépenses découlant ou liés à (i) votre violation des présentes Conditions et/ou (ii) votre utilisation de citoyen, y compris tout contenu que vous pouvez soumettre ou publier sur citoyen.</p>
<h5>Dispositions Supplémentaires</h5>
<p>Les présentes conditions et votre utilisation de citoyen sont régies par les lois de la République fédérale du Nigéria, sans donner effet à ses dispositions relatives aux conflits de lois. Vous acceptez expressément que la juridiction exclusive pour toute réclamation ou litige en vertu des présentes Conditions et/ou de votre utilisation de citoyen relève des tribunaux situés en République fédérale du Nigéria, et vous acceptez en outre expressément de vous soumettre à la juridiction personnelle de ces tribunaux aux fins de la poursuite de toute réclamation ou action. Si une disposition particulière des présentes Conditions s'avère inapplicable, cela n'affectera pas les autres dispositions.</p>
<p>Vous ne pouvez pas céder vos droits en vertu des présentes. Nous pouvons céder nos droits en vertu des présentes à tout moment sans restriction.</p>
<p>Nous pouvons modifier les présentes Conditions à tout moment, alors assurez-vous de vérifier régulièrement. En continuant à utiliser ou à vous connecter à citoyen après la modification des présentes Conditions, vous indiquez votre accord avec les Conditions révisées. Si vous n'acceptez pas les modifications, vous devez cesser d'utiliser ou de vous connecter à citoyen.</p>
<p>citoyen peut contenir des liens vers des sites tiers. Veuillez noter que nous ne contrôlons ni n'approuvons ces sites, ni les biens ou services vendus sur ceux-ci.</p>
<p>Veuillez noter que nous nous engageons à assurer la sécurité et la protection de toutes les informations personnelles que nous détenons et à sauvegarder les droits des sujets en matière de protection des données. Nous sommes conformes aux exigences réglementaires applicables en matière de protection des données, et nos processus internes de protection des données continuent d'être examinés pour garantir leur pleine optimisation conformément aux lois applicables en matière de protection des données et aux changements réglementaires.</p>
<p>Veuillez lire notre Politique de confidentialité pour plus d'informations sur la façon dont nous traitons vos données personnelles.</p>
`;

export default termsOfServiceFR;
