const termsOfServiceSW = `
<p>Karibu kwenye e-raia.ng au e-raia. e-raia inatolewa na Biosec Solutions Limited. Tafadhali soma Sheria na Masharti ("Masharti") na Sera ya Faragha kwa makini kwa sababu ni makubaliano ya kisheria kati yako na Biosec Solutions Limited, ("Biosec" au "Sisi"). Masharti haya yanaelezea matarajio na kuweka haki na wajibu wetu kuhusiana na matumizi yako ya e-raia.</p>
<p>Masharti haya yanatawala matumizi yako ya e-raia yaliyounganishwa na Masharti haya. Katika Masharti haya, e-raia.ng inarejelea majukwaa yote ya e-raia yanayomilikiwa na kudhibitiwa na Biosec na huduma zinazotolewa juu yake. Unakubali Masharti haya na Sera yetu ya Faragha kiotomatiki kwa kutumia au kuingia kwenye e-raia.</p>
<p>Masharti haya yanaweza kubadilika mara kwa mara. Tutachapisha mabadiliko yoyote kwenye Masharti yetu kwenye e-raia na tutakujulisha kuhusu sasisho kwa kurekebisha tarehe ya "Ilisasishwa Mara ya Mwisho" iliyoorodheshwa juu ya ukurasa. Ikiwa mabadiliko ni makubwa, tutajitahidi kutoa notisi ya wazi zaidi (kama vile notisi ya barua pepe).</p>
<p>Tafadhali kumbuka kwamba tunaweza sasa au wakati ujao kutoa huduma tofauti. Matumizi yako ya bidhaa au huduma zetu hutolewa na Biosec kwa mujibu wa makubaliano tofauti yaliyotekelezwa kwa mkono au kidijitali. Masharti hayo ya ziada yanakuwa sehemu ya makubaliano yako nasi ikiwa unatumia huduma au kuingia kwenye e-raia.</p>

<h5>Uwezo wa Kukubali Masharti</h5>
<p>Unathibitisha kwamba una miaka 18 na zaidi, au una idhini halali ya mzazi au mlezi, na una uwezo kamili na umahiri wa kuingia katika masharti, vigezo, wajibu, uthibitisho, uwakilishi, na dhamana zilizowekwa katika Masharti haya, na kuzingatia na kutii Masharti haya.</p>

<h5>Akaunti Yako</h5>
<p>Unaweza kuunda akaunti na kubainisha neno la siri ili kutumia huduma au vipengele fulani kwenye e-raia. Unakubali kwamba taarifa zote unazotupa zitakuwa kamili, za kweli, na sahihi. Ikiwa taarifa zako zitabadilika wakati wowote, unakubali kwamba zitasasishwa kuakisi mabadiliko hayo.</p>
<p>Huwezi kushiriki akaunti yako au neno la siri na mtu mwingine yeyote. Tafadhali weka neno lako la siri kwa usiri, na utakuwa na jukumu la pekee la kulinda jina lako la mtumiaji na neno la siri na kwa matumizi yote ya e-raia kwa kutumia barua pepe yako au neno la siri. Ikiwa unaamini kwamba akaunti yako imeathiriwa wakati wowote, tafadhali tujulishe kupitia info@e-raia.ng. Utakuwa na dhima ya pekee kwa matumizi yoyote ya e-raia chini ya akaunti yako na neno la siri. Unakubali kutujulisha mara moja ikiwa utagundua matumizi yoyote yasiyoidhinishwa au ufichuzi wa neno lako la siri. Tunahifadhi haki ya kukataa matumizi ya au kubatilisha matumizi ya jina lolote la mtumiaji kwa hiari yetu.</p>

<h5>Marekebisho</h5>
<p>Tunahifadhi haki ya kurekebisha e-raia wakati wowote, kwa notisi au bila notisi kwako. Kwa mfano, tunaweza kuongeza au kuondoa utendaji au vipengele, na tunaweza kusimamisha au kuacha kipengele fulani kabisa. Pia tunahifadhi haki ya kutoza ada kwa vipengele vyetu vyovyote wakati wowote. Ikiwa hupendi mabadiliko yoyote, unaweza kuacha kutumia e-raia wakati wowote.</p>

<h5>Kukomesha</h5>
<p>Tunaweza wakati wowote kuacha kuendesha sehemu au yote au kuzima kwa kuchagua vipengele fulani vya e-raia. Unaweza kuacha kutumia e-raia wakati wowote, mradi tu unakubali na kukubali kwamba maudhui yoyote uliyochapisha kabla ya wakati huo yataendelea kupatikana kwenye na kupitia e-raia. Tunaweza kukomesha matumizi yako ya e-raia ikiwa utakiuka Masharti haya kwa notisi au bila notisi ya awali kwako.</p>

<h5>Matumizi Yako ya e-raia</h5>
<p>Matumizi yako ya e-raia yatazingatia sheria zote zinazotumika. Hautajaribu kukwepa au kukiuka kipengele chochote cha usalama cha e-raia, ikiwa ni pamoja na kufikia vipengele vyovyote vya e-raia, maeneo shirikishi, taarifa au wasifu ambao huna ruhusa au maudhui au taarifa nyingine ambazo si za wewe. Kama sehemu ya matumizi yako ya e-raia, unakubali kwamba hutafanya yafuatayo:</p>
<ul>
<li>kuingilia, au kujaribu kuingilia, shughuli za kawaida za e-raia au matumizi ya mtumiaji mwingine yeyote wa e-raia, ikiwa ni pamoja na kupakia kupita kiasi, kufurika, kutuma barua taka au kuvuruga e-raia au mifumo yake ya msingi au kwa kubadilisha wasifu wowote, hakiki au taarifa nyingine zinazotolewa na mtumiaji yeyote;</li>
<li>kuchapisha, kushiriki, kuunganisha au kuwasilisha Maudhui yoyote au nyenzo ambayo ni ya kukashifu, ya kudhalilisha, yanayokiuka faragha au haki za utangazaji, ya kichafu, ya matusi, ya staha, ya ponografia au ya unyonyaji;</li>
<li>kutumia e-raia kusumbua, kudhulumu, kutishia, kufedhehesha, kufuatilia au kumtisha mtumiaji mwingine yeyote au mtu mwingine yeyote; kuchapisha, kushiriki, kuunganisha au kuwasilisha maudhui yoyote au nyenzo inayojumuisha matamshi ya chuki, inayokuza vurugu dhidi ya kikundi chochote au mtu au vinginevyo inayokera;</li>
<li>kuchapisha, kushiriki, kuunganisha au kuwasilisha maudhui yoyote au nyenzo ambayo ni ya ulaghai, ya uwongo, ya kupotosha au ya udanganyifu;</li>
<li>kuchapisha, kushiriki au kufichua taarifa yoyote ya kibinafsi inayomtambulisha mtu mwingine yeyote;</li>
<li>kujifanya au kupendekeza kwa uwongo au kudai uhusiano na mtu au shirika lingine lolote;</li>
<li>kutafuta kupata mapato kutoka kwa e-raia, ikiwa ni pamoja na kutoa hakiki au vikubali kwa malipo au maslahi mengine kutoka kwa mtu mwingine yeyote;</li>
<li>kukusanya, kuhifadhi au kuchambua taarifa kuhusu watumiaji wengine, isipokuwa kama idhinishwa na Mtumiaji huyo;</li>
<li>kutufungulia dhima yoyote ya madai ya kiraia au jinai; au</li>
<li>kuvunja sheria yoyote inayotumika au kuhimiza tabia ambayo ingekuwa kosa la jinai.</li>
</ul>
<p>Ikiwa (kwa hiari yetu pekee) tutaamua kwamba umefanya vibaya, tunahifadhi haki ya kuondoa Maudhui, kukomesha akaunti yako, kukukataza kutumia e-raia, na kuchukua hatua nyingine zozote za kisheria zinazofaa. Kutumia e-raia hakukupi umiliki wa haki zozote za uvumbuzi kwa Maudhui unayopata. Huwezi kutumia Maudhui kutoka kwa e-raia isipokuwa upate ruhusa kutoka kwetu au mmiliki wake, au isipokuwa umeruhusiwa vinginevyo na sheria. Unapotumia e-raia au kutuma mawasiliano kwetu kupitia e-raia, unawasiliana nasi kwa njia ya elektroniki. Unakubali kupokea kwa njia ya elektroniki mawasiliano yoyote yanayohusiana na matumizi yako ya e-raia. Tunaweza kuwasiliana nawe kwa barua pepe au kwa kuchapisha notisi kwenye e-raia. Unakubali kwamba makubaliano yote, notisi, ufichuzi na mawasiliano mengine yanayotolewa kwako kwa njia ya elektroniki yanakidhi hitaji lolote la kisheria kwamba mawasiliano hayo yawe kwa maandishi. Notisi zote kutoka kwetu zinazokusudiwa kupokelewa nawe zitachukuliwa kuwa zimetolewa na kuanza kutumika zinapotumwa kwa anwani ya barua pepe unayotupa. Tafadhali kumbuka kwamba kwa kuwasilisha Maudhui, kuunda akaunti ya mtumiaji au vinginevyo kutupa anwani yako ya barua pepe, anwani ya posta au nambari ya simu, unakubali kwamba sisi au mawakala wetu tunaweza kuwasiliana nawe kwa anwani hiyo au nambari hiyo kwa njia inayoendana na Sera yetu ya Faragha.</p>

<h5>Malipo ya Mtandaoni</h5>
<p>Huduma yetu inaruhusu malipo ya mtandaoni ya ada muhimu kwa kutumia huduma za wengine za malipo ya mtandaoni zinazosaidia malipo ya mtandaoni. Utawajibika kwa taarifa za malipo unazotoa kwa huduma hizi za malipo ya mtandaoni na hatutawajibishwa kwa taarifa zozote batili zilizotolewa wala hatutawajibishwa kwa kuanzisha, utekelezaji, maendeleo, wala kukamilika kwa mchakato wowote wa kurejesha fedha unaowezekana unaojitokeza wakati wa matumizi yako ya Suluhisho na Huduma zetu.</p>
<p>Unahimizwa kuhakikisha usahihi wa vigezo vya utafutaji. Hutarejeshwa fedha ikiwa taarifa za utafutaji si sahihi au hazipo.</p>

<h5>Ufikiaji wa Mhusika wa Data kwa Taarifa Zilizosajiliwa</h5>
<p>Huduma yetu inaendeshwa kwa idhini inapotumika. Idhini ya mhusika wa data inahitajika kabla taarifa kufichuliwa kwa mtumiaji anayeomba. Hutarejeshwa fedha pale ambapo mhusika wa data hana ufikiaji wa nambari ya simu iliyosajiliwa au anwani ya barua pepe kwenye hifadhidata husika, au ikiwa mhusika wa data anakataa idhini.</p>

<h5>Usahihi na Uadilifu wa Data</h5>
<p>e-raia ni mkusanyaji wa data na inarudisha tu matokeo yaliyoripotiwa na vyanzo vya data vya taasisi zinazotakiwa kuripoti. e-raia hawajibiki kwa usahihi au uadilifu wa data yoyote iliyorejeshwa, wala e-raia haitoi dhamana hiyo. Maswali yoyote kuhusu usahihi au uadilifu wa data yanapaswa kuelekezwa kwa taasisi inayotakiwa kuripoti.</p>

<h5>Haki Miliki</h5>
<p>Kati yako na Biosec, e-raia, ikijumuisha maudhui yote, graphics, sauti, video, picha, chapa za biashara, alama za Jukwaa, nembo na nyenzo nyingine kwenye e-raia, na programu yake ya msingi ("Programu"), algorithimu, hifadhidata, muonekano na mpangilio, ni mali miliki ya Biosec, chini ya ulinzi wa hakimiliki na ulinzi mwingine wa mali miliki. Alama na nembo ya e-raia ni chapa za biashara za Biosec. Haki zote katika na kwa e-raia na Programu ambazo hazijatolewa wazi hapa zimehifadhiwa na sisi. Tunakupa na unakubali leseni isiyo ya kipekee, isiyoweza kuhamishwa, inayoweza kubatilishwa ya kutumia Programu kwa matumizi yako mwenyewe ya e-raia na kwa mujibu wa Masharti haya.</p>
<p>Ikiwa unaamini kwamba Maudhui yoyote kwenye e-raia yanakiuka hakimiliki zako, unaweza kuomba kuondolewa kwa Maudhui kutoka kwa e-raia (au kuzima ufikiaji wa Maudhui hayo) kwa kuwasiliana nasi kupitia dpo@biosec.com.ng. Tumejitolea kutumia juhudi za kibiashara zinazofaa kuchunguza kila madai.</p>

<h5>Mitandao ya Kijamii</h5>
<p>e-raia inaweza kujumuisha vipengele vinavyofanya kazi pamoja na tovuti fulani za mitandao ya kijamii za watu wengine unazotembelea kama vile Facebook, Instagram, YouTube, Vimeo, na Twitter. Ingawa matumizi yako ya vipengele hivi yanatawaliwa na Masharti haya, ufikiaji wako na matumizi ya tovuti za mitandao ya kijamii za watu wengine yanatawaliwa na sheria na masharti na makubaliano mengine yaliyochapishwa kwenye tovuti hizi. Wewe ndiye unawajibika kuhakikisha kwamba matumizi yako ya tovuti hizo yanazingatia sheria na masharti yoyote yanayotumika au makubaliano mengine.</p>

<h5>Kanusho la Dhamana</h5>
<p>E-RAIA INATOLEWA KWA MSINGI WA "KAMA ILIVYO" NA "KAMA INAVYOPATIKANA". KWA HIZI TUNATAKA UWAKILISHO NA DHAMANA ZOTE, ZA KWAZI AU ZILIZODHIRIWA, KUHUSIANA NA E-RAIA AU MAUDHUI YAKE, IKIWA NI PAMOJA NA LAKINI SIO TU KWA DHAMANA ZILIZODHIRIWA ZA UUZAJI, KUTOSHELEZA KWA MADHUMUNI YOYOTE MAALUM, NA KUTOKUKIUKA KWA HAKI ZA MALI MILIKI ZA WATU WENGINE. BIOSEC HATOI DHAMANA AU UWAKILISHI KUHUSU USAHIHI, UIMARA, USALAMA AU UKAMILIFU WA E-RAIA AU MAUDHUI YAKE, AU VINGINEVYO. HATUTOI DHAMANA AU HAKIKISHO KUHUSU UPATIKANAJI AU KUTEGEMEKA KWA E-RAIA AU KWAMBA E-RAIA ITAPATIKANA KWA WAKATI MAALUM. MATUMIZI YOTE YA E-RAIA NI KWA HATARI YAKO MWENYEWE. IKIWA HUJARIDHISHWA NA E-RAIA, SULUHISHO LAKO LA PEKEE NI KUACHA KUTUMIA NA KUPATA KUREJESHEWA MALIPO YA MAPEMA, IWAPO YAPO, KAMA ILIVYOWEKWA KATIKA MASHARTI HAYA.</p>

<h5>Kizuizi cha Dhima</h5>
<p>ISIPOKUWA PALE ILIPOZUIWA NA SHERIA, BIOSEC HATAWAJIBIKA KWA UHARIBIFU WOWOTE WA MOJA KWA MOJA, USIO WA MOJA KWA MOJA, MAALUM, WA KUTOKEA, WA MFUATANO, AU WA KIOGOFANO UNAOTOKANA NA MATUMIZI YAKO YA E-RAIA AU MATUMIZI YA MTU MWINGINEYE YEYOTE WA E-RAIA. VIZUIZI HIZI ZINAJUMUISHA, BILA KIKOMO, UHARIBIFU KWA FAIDA ZILIZOPOTEA, DATA ILIYOPOTEA, KUSHINDWA KWA TARAKILISHI, AU UHALIFU WA HAKI ZAKO NA MTU MWINGINEYE YEYOTE, HATA KAMA MTU AMEONYWA KUHUSU UWEZEKANO WA HIZO NA BILA KUJALI NADHARIA YA KISHERIA AU YA HAKI AMBAYO MADAI YANATEGEMEA. KWA HALI YOYOTE, DHIMA YA JUMLA YA BIOSEC KWA MTUMIAJI YEYOTE BINAFSI KUHUSIANA NA MATUMIZI YA E-RAIA HAITAZIDI JUMLA YA KIASI ULICHOTULIPA KWA MATUMIZI YA E-RAIA, IWE DHIMA HIYO INATEGEMEA MKATABA, MAKOSA AU VINGINEVYO.</p>

<h5>Fidia</h5>
<p>Kwa hili unakubali kulipa fidia, kutetea na kuwashikilia Biosec na washirika wake na kila mmoja wa wenyewe, wanachama, wakurugenzi, maafisa, wasimamizi, wafanyakazi, wakandarasi huru, wakandarasi wa chini, mawakala na wawakilishi ("Wahusika Waliolindwa") bila hatari kutoka kwa madai yoyote, sababu ya hatua, shauri, dhima, kodi, uharibifu, hasara, ada za wakili, gharama na matumizi yanayotokana na au kuhusiana na (i) uvunjaji wako wa Masharti haya na/au (ii) matumizi yako ya e-raia, ikiwa ni pamoja na Maudhui yoyote unayoweza kuwasilisha au kuchapisha kwenye e-raia.</p>

<h5>Maelezo ya Ziada</h5>
<p>Masharti haya na matumizi yako ya e-raia yanatawaliwa na sheria za Jamhuri ya Shirikisho la Nigeria, bila kutoa athari kwa masharti yake ya mgongano wa sheria. Unakubali kwa uwazi kwamba mamlaka ya kipekee kwa madai yoyote au mgogoro chini ya Masharti haya na/au matumizi yako ya e-raia yapo katika mahakama zilizoko katika Jamhuri ya Shirikisho la Nigeria, na zaidi unakubali kwa uwazi kuwasilisha kwa mamlaka ya kibinafsi ya mahakama hizo kwa madhumuni ya kusikilizwa kwa madai au hatua yoyote kama hiyo. Ikiwa itatokea kwamba kipengele fulani katika Masharti haya hakitumiki, hiyo haitaathiri kipengele kingine chochote.</p>
<p>Huenda ukagawa haki zako chini ya haya. Tunaweza kugawa haki zetu chini ya haya wakati wowote bila kizuizi.</p>
<p>Tunaweza kurekebisha Masharti haya wakati wowote kwa hivyo hakikisha unaangalia mara kwa mara. Kwa kuendelea kutumia au kuingia kwenye e-raia baada ya Masharti haya kubadilika, unaonyesha kukubali kwako Masharti yaliyorekebishwa. Ikiwa hukubaliani na mabadiliko, unapaswa kuacha kutumia au kuingia kwenye e-raia.</p>
<p>e-raia inaweza kuwa na viungo vya tovuti za watu wengine. Tafadhali kumbuka kwamba hatuzidhibiti wala kuzikubali tovuti hizo, au bidhaa au huduma zozote zinazouzwa kwenye tovuti hizo.</p>
<p>Tafadhali kumbuka kwamba tumejitolea kuhakikisha usalama na ulinzi wa taarifa zote za kibinafsi tunazoshikilia na kulinda haki za wahusika wa data kwa faragha na ulinzi wa data. Tunatii mahitaji yanayotumika ya udhibiti kuhusu faragha na ulinzi wa data, na michakato yetu ya ndani ya ulinzi wa data inaendelea kupitiwa ili kuhakikisha imeboreshwa kikamilifu kwa mujibu wa sheria zinazotumika za ulinzi wa data na mabadiliko ya mahitaji ya udhibiti.</p>
<p>Tafadhali soma Sera yetu ya Faragha kwa taarifa kuhusu jinsi tunavyochakata data yako ya kibinafsi.</p>
`;
export default termsOfServiceSW;
